source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'iOSdemo' do
  use_frameworks!
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      # ensure all pods target iOS 12.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end